### ISSUE TITLE
Empty page after bibliography

### ISSUE THREAD

**Issue by StefanFW** [schnes4/dhbw-heidenheim-latex-template#22]
After compiling there is a empty page after bibliography

**Comment by nobodypb** [comment]
This is the wanted behaviour, since the template is optimated as book. The bibliography will take double pages in space and add an empty page if necessary to do so.

**Comment by StefanFW** [comment]
Ok I see....

I'll close this Issue but please let us know who you are 😜 (Sebastian?)
