### ISSUE TITLE
Literaturverzeichnis

### ISSUE THREAD

**Issue by marten-sch** [schnes4/dhbw-heidenheim-latex-template#4]
Das Literaturverzeichnis fehlt noch. Zudem kommt es beim Kompelieren zu den Fehlern:

Fehler: Eine Kommandoersetzung ungültig
    Eltern-Befehl: bibliography
    Hauptbefehl: recompile-bibliography

Fehler: Eine Kommandoersetzung ungültig
    Eltern-Befehl: bibliography
    Hauptbefehl: bibliography

Fehler: Eine Kommandoersetzung ungültig
    Eltern-Befehl: bibliography
    Hauptbefehl: bibliography

**Comment by marten-sch** [comment]
Zu lösen in den Einstellungen von Latex
http://texwelt.de/wissen/fragen/1909/wie-verwende-ich-biber-in-meinem-editor

**Comment by StefanFW** [comment]
Bitte noch in Readme eintragen
Dann können alle davon profitieren (du bist nicht der erste der das Problem adressiert hat)

**Comment by nobodypb** [comment]
What about adding a script for cleaning and recompiling as fallback solution, if the editor just won't compile. I've come across several situations where the editor just didn't compile, but from console it worked.

**Comment by ghost** [comment]
This issue is not a problem caused by this template / project. It's clearly an issue with your editor and therefore shouldn't exist as an issue.

Therefore i'll close this issue.
